// <auto-generated />
namespace _02._04._2019_ND.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Mogration_4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Mogration_4));
        
        string IMigrationMetadata.Id
        {
            get { return "201904020435042_Mogration_4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
